### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by hsiboy** [JosephHewitt/wardriver_rev3#61] opened 2023-05-27 10:24 UTC
Hi,

This doesn't seem to be covered in the questions, but how is the removal of power and cleanly closing the file handled?

There is no capacitor on board to sustain power to close the file cleanly.
To me it just looks like whatever state we are in at power removal is what we get. In my case, a corrupted SD card after a long war driving session.

Not complaining, I came here to help make it more robust 👍

**Comment by JosephHewitt** [comment] 2023-05-27 11:36
Hi,

Thanks for the great question!

There is nothing in the software to handle closing the file cleanly so your assumption was correct.

The wardriver calls `flush` on a regular basis so that data is written to the SD card frequently rather than being lost when the power is removed. I have not (yet) seen a case of the SD card becoming corrupt, generally you just get a half-written line if you remove power during a write but this does not cause any problems (aside from a single entry not being sent to Wigle).

Have you tried opening your SD card directly with a hex editor? Maybe this will let you pull off the captured data if the corruption is within the file allocation table.

I suspect this may be an isolated issue since I have not seen anything like this before or heard of it happening to others. I would definitely like to find out the cause though. Does your SD card show any other signs of problems such as errors when you try to format it or problems when used in other devices?

**Closed** 2023-07-07 19:23 UTC
