### ISSUE TITLE
Text doesn't seem aligned on the OLED screen

### ISSUE THREAD

**Issue by hyuma78** [JosephHewitt/wardriver_rev3#144] opened 2024-01-26 13:59 UTC
Hi, I just built my own wardriver, but I have some strange issue. When the texts appears on my oled 0.91 128x32px it seems like not aligned as you can see on the screenshot that I have attached here. I resoldered, change wires, test continuity between pads of the OLED but no luck. I also repogrammed 2-3 times the ESP32 but same result. I also tested the I2C protocol of the screen with an arduino sketch and it's "3c". I tried to replace the screen but I have the same issue. At this point I need your help to try to troubleshooting this. Thanks in advance!

![IMG_20240126_144445](https://github.com/JosephHewitt/wardriver_rev3/assets/27858616/48bf59a7-9782-4380-84f0-d377702dcc9e)
![IMG_20240126_144511](https://github.com/JosephHewitt/wardriver_rev3/assets/27858616/9830c0d7-8998-492e-9a99-37f53e5a900e)
![IMG_20240126_144513](https://github.com/JosephHewitt/wardriver_rev3/assets/27858616/b9d8eecd-4623-4b90-99fd-d878bb9f533a)

**Comment by hyuma78** [comment] 2024-01-26 22:02
No, I don't have any other ESP32, except for that problem, the rest seems to work, do you think it depends on some library that I installed? I'm using Arduino IDE 2.2.1, and I didn't tried by compiling myself yet.

**Comment by JosephHewitt** [comment] 2024-01-28 19:17
If you install from binary, it will rule out any problems caused by libraries etc. 

My gut feeling is this is either a faulty ESP32 or a bad batch of LCDs.

**Comment by hyuma78** [comment] 2024-01-31 10:15
I've done a really insane thing :D ... I basically hot air desoldered every components of the esp32 (resistors, ic, etc...) and resoldered all together and now it seems that there are no problems, I also edited the code to works with 128x64 display. I will keep you updated if this issue is resolved

**Comment by JosephHewitt** [comment] 2024-04-10 19:45
Hi,

Thanks for informing us on how you fixed the issue. Please feel free to reopen this issue if the problem comes back, but I am assuming this is fixed now based on your last comment.

**Closed by JosephHewitt** 2024-04-10 19:45 UTC
