### ISSUE TITLE
Find Stalkers - a script to identify devices spotted at multiple locations

### ISSUE THREAD

**Issue by grymoire** [JosephHewitt/wardriver_rev3#19] opened 2022-09-02 14:12 UTC
I added a new shell/awk script that looks at *.csv files and identies MAC addresses seen at multiple locations.
It can identify the MAC address of people you come into contact frequently.

It's in my repository clone
https://github.com/grymoire/wardriver_rev3/tree/main/scripts

**Comment by JosephHewitt** [comment] 2022-09-03 12:44
Hi,

Thanks for sharing.

Since this is not a bug report or issue I need to close this.

**Closed by JosephHewitt** 2022-09-03 12:44 UTC

**Comment by grymoire** [comment] 2022-09-03 12:49
Thanks. I wasn't sure how to share this.
